//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hospital.Data.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Doktor
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Doktor()
        {
            this.Tedavi = new HashSet<Tedavi>();
            this.HastaKayit = new HashSet<HastaKayit>();
        }
    
        public int doktorID { get; set; }
        public string doktorAdi { get; set; }
        public string doktorSoyadi { get; set; }
        public string doktorTelefon { get; set; }
        public string doktorUzmanlikAlani { get; set; }
        public Nullable<int> bolumID { get; set; }
    
        public virtual Bolum Bolum { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tedavi> Tedavi { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HastaKayit> HastaKayit { get; set; }
    }
}
