//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hospital.Data.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class HastaKayit
    {
        public int HastaKayitID { get; set; }
        public string HastaAdi { get; set; }
        public string HastaSoyadi { get; set; }
        public string HastaTc { get; set; }
        public string HastaSikayet { get; set; }
        public Nullable<int> bolumID { get; set; }
        public Nullable<int> doktorID { get; set; }
    
        public virtual Bolum Bolum { get; set; }
        public virtual Doktor Doktor { get; set; }
    }
}
